[package]
name = "athena-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



[dependencies.athena-clientsdk]
path = "../athena-clientsdk"
version = "0.1.0"